package neptuno;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author User
 */
public class Frmenus extends javax.swing.JFrame {

    /**
     * Creates new form Frmenus
     */
    public Frmenus() {
        initComponents();
        this.getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jdpContenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenuItem();
        mnuEnvios = new javax.swing.JMenuItem();
        mnuProv = new javax.swing.JMenuItem();
        mnuCategorias = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmenu2 = new javax.swing.JMenu();
        mnuFactura = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnuMejores = new javax.swing.JMenuItem();
        mnuVentasCategoria = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpContenedorLayout = new javax.swing.GroupLayout(jdpContenedor);
        jdpContenedor.setLayout(jdpContenedorLayout);
        jdpContenedorLayout.setHorizontalGroup(
            jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );
        jdpContenedorLayout.setVerticalGroup(
            jdpContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );

        jMenu1.setText("Mantenimiento");

        mnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.SHIFT_MASK));
        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClientes);

        mnuEmpleados.setText("Empleados");
        mnuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEmpleados);

        mnuEnvios.setText("Compañías de Envíos");
        mnuEnvios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEnviosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuEnvios);

        mnuProv.setText("Proveedores");
        mnuProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProvActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProv);

        mnuCategorias.setText("Categorías");
        mnuCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCategorias);

        mnuProductos.setText("Productos");
        mnuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProductosActionPerformed(evt);
            }
        });
        jMenu1.add(mnuProductos);

        jMenuItem1.setText("Pedidos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jmenu2.setText("Facturacion");
        jmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenu2ActionPerformed(evt);
            }
        });

        mnuFactura.setText("Factura");
        mnuFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFacturaActionPerformed(evt);
            }
        });
        jmenu2.add(mnuFactura);

        jMenuBar1.add(jmenu2);

        jMenu6.setText("Reporte");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        mnuMejores.setText("Los 10 mejores clientes");
        mnuMejores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMejoresActionPerformed(evt);
            }
        });
        jMenu6.add(mnuMejores);

        mnuVentasCategoria.setText("Ventas por Categoria");
        mnuVentasCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVentasCategoriaActionPerformed(evt);
            }
        });
        jMenu6.add(mnuVentasCategoria);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Acerca de");

        jMenuItem4.setText("Acerca de");
        jMenu7.add(jMenuItem4);

        jMenuItem5.setText("Ayuda");
        jMenu7.add(jMenuItem5);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpContenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEmpleadosActionPerformed
          FrmEmpleados frmempleados=new FrmEmpleados();
        frmempleados.setVisible(true);
        jdpContenedor.add(frmempleados);//se agrega el Jinternalform  
    }//GEN-LAST:event_mnuEmpleadosActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
       
        FrmClientes frmclientes=new FrmClientes();
        frmclientes.setVisible(true);
        jdpContenedor.add(frmclientes);//se agrega el Jinternalform 
        
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProvActionPerformed
      FrmProveedores frmproveedores=new FrmProveedores();
        frmproveedores.setVisible(true);
        jdpContenedor.add(frmproveedores);//se agrega el Jinternalform 
    }//GEN-LAST:event_mnuProvActionPerformed

    private void mnuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProductosActionPerformed
      FrmProductos frmproductos=new FrmProductos();
        frmproductos.setVisible(true);
        jdpContenedor.add(frmproductos);//se agrega el Jinternalform 
    }//GEN-LAST:event_mnuProductosActionPerformed

    private void jmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenu2ActionPerformed
       
        
    }//GEN-LAST:event_jmenu2ActionPerformed

    private void mnuFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFacturaActionPerformed
        FrmFactura frmfacturas=new FrmFactura();
        frmfacturas.setVisible(true);
        jdpContenedor.add(frmfacturas);//se agrega el Jinternalform 
    }//GEN-LAST:event_mnuFacturaActionPerformed

    private void mnuCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriasActionPerformed
        FrmCategorias frmcategoria=new FrmCategorias();
        frmcategoria.setVisible(true);
        jdpContenedor.add(frmcategoria);//se agrega el Jinternalform 
    }//GEN-LAST:event_mnuCategoriasActionPerformed

    private void mnuEnviosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEnviosActionPerformed
       FrmCompaniasEnvios frmcompania=new FrmCompaniasEnvios();
        frmcompania.setVisible(true);
        jdpContenedor.add(frmcompania);//se agrega el Jinternalform 
    }//GEN-LAST:event_mnuEnviosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmPedidos frmfpedidos=new FrmPedidos();
        frmfpedidos.setVisible(true);
        jdpContenedor.add(frmfpedidos);//se agrega el Jinternalform 
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        FrmPedidos frmPedidos=new FrmPedidos();
        frmPedidos.setVisible(true);
        jdpContenedor.add(frmPedidos);//se agrega el Jinternalform 
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void mnuMejoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMejoresActionPerformed
            FrmReporteClientes frmreporte=new FrmReporteClientes();
        frmreporte.setVisible(true);
        jdpContenedor.add(frmreporte);//se agrega el Jinternalform 
    }//GEN-LAST:event_mnuMejoresActionPerformed

    private void mnuVentasCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVentasCategoriaActionPerformed
       FrmVentasporCategoria frmventas=new FrmVentasporCategoria();
        frmventas.setVisible(true);
        jdpContenedor.add(frmventas);//se agrega el Jinternalform 
    }//GEN-LAST:event_mnuVentasCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JDesktopPane jdpContenedor;
    private javax.swing.JMenu jmenu2;
    private javax.swing.JMenuItem mnuCategorias;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuEmpleados;
    private javax.swing.JMenuItem mnuEnvios;
    private javax.swing.JMenuItem mnuFactura;
    private javax.swing.JMenuItem mnuMejores;
    private javax.swing.JMenuItem mnuProductos;
    private javax.swing.JMenuItem mnuProv;
    private javax.swing.JMenuItem mnuVentasCategoria;
    // End of variables declaration//GEN-END:variables
}
