package neptuno;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author User
 */
public class FrmPedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPedidos
     */
    public FrmPedidos() {
        initComponents();
             this.getContentPane().setBackground(Color.white);
        JButton[] botones={btnNuevo,btnGuardar,btnModificar,btnElminar,btnImprimir};
        JLabel[] label={lblPedido,lblCliente,lblEmpleado,lblPedido2,lblEntrega,lblEnvio,lblForma,lblCargo,lblDest,lblDireccion,lblCiudad};
 JLabel[] label3={lblRegion,lblCodigo,lblPais};
JTextField[] texto1={txtidped,txtidcliente,txtidempleado,txtfpedido,txtfentrega,txtfeenvio,txtformaenvio,txtcargo,txtdestinatario,txtdirdest,txtciuddest};
JTextField[] texto3={txtregdest,txtcodpostdes,txtpaisdest};
JTextField[] texto2={txtbuscarporid,txtbucarporcompania};
 JLabel[] label2={lblID,lblname2};
 jSeparator1.setBounds(105, 70, 570, 10);
jSeparator3.setBounds(675, 70, 10, 660);
jSeparator4.setBounds(10, 728, 665, 10);
jSeparator6.setBounds(10, 500, 10, 230);
jSeparator7.setBounds(10, 75, 10, 400);
jSeparator2.setBounds(80, 490, 595, 10);
lblMantenimiento.setBounds(12, 57, 100, 20);
lblBusqueda.setBounds(12, 478, 100, 20);
btnGuardar.setEnabled(false);
btnModificar.setEnabled(false);
btnElminar.setEnabled(false);
btnImprimir.setEnabled(false);
 DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
Date date = new Date();
txtfpedido.setText(dateFormat.format(date));
txtfentrega.setText(dateFormat.format(date));
txtfeenvio.setText(dateFormat.format(date));

 int separacionbtn=30;
        int separacionlbl=90;
        int separaciontxt=170;
        for(JButton btn:botones)
        {
            btn.setBounds(separacionbtn,20,30,30);
            separacionbtn+=30;
        }
        
        
         for(JLabel lbl:label)
        {
            lbl.setBounds(90,separacionlbl,150,30);
            separacionlbl+=35;
        }
         
        separacionlbl=90; 
          for(JLabel lbl:label3)
        {
            lbl.setBounds(375,separacionlbl,150,30);
            separacionlbl+=35;
        }
         
          separacionlbl=100;
        
              for(JTextField txt:texto1)
        {
            txt.setBounds(230,separacionlbl,100,20);
            separacionlbl+=35;
        }
              
              
               separacionlbl=100;
        
              for(JTextField txt:texto3)
        {
            txt.setBounds(500,separacionlbl,100,20);
            separacionlbl+=35;
        }
              
               separaciontxt=160;
          for(JTextField txt:texto2)
        {
            txt.setBounds(separaciontxt,535,100,20);
            separaciontxt+=310;
        }
          
           separacionlbl=100;
        for(JLabel lbl:label2)
        {
            lbl.setBounds(separacionlbl,525,120,30);
            separacionlbl+=250;
        }
    }
    
            public void Habilitarbtn()
    {
     JTextField[] texto1={txtidped,txtidcliente,txtidempleado,txtfpedido,txtfentrega,txtfeenvio,txtformaenvio,txtcargo,txtdestinatario,txtdirdest,txtciuddest,txtregdest,txtcodpostdes,txtpaisdest};

           
       if(!texto1[0].getText().isEmpty() && !texto1[1].getText().isEmpty() && !texto1[2].getText().isEmpty() &&
          !texto1[3].getText().isEmpty() && !texto1[4].getText().isEmpty() && !texto1[5].getText().isEmpty() &&
          !texto1[6].getText().isEmpty() && !texto1[7].getText().isEmpty() && !texto1[8].getText().isEmpty() &&
          !texto1[9].getText().isEmpty() && !texto1[10].getText().isEmpty() && !texto1[11].getText().isEmpty() &&
          !texto1[12].getText().isEmpty() && !texto1[13].getText().isEmpty()  )
       {
           btnGuardar.setEnabled(true);
       }
       else{
           btnGuardar.setEnabled(false);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblMantenimiento = new javax.swing.JLabel();
        lblBusqueda = new javax.swing.JLabel();
        lblPedido = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblPedido2 = new javax.swing.JLabel();
        lblEntrega = new javax.swing.JLabel();
        lblEnvio = new javax.swing.JLabel();
        lblForma = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        lblDest = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        txtdirdest = new javax.swing.JTextField();
        txtciuddest = new javax.swing.JTextField();
        txtdestinatario = new javax.swing.JTextField();
        txtcargo = new javax.swing.JTextField();
        txtformaenvio = new javax.swing.JTextField();
        txtfeenvio = new javax.swing.JTextField();
        txtfentrega = new javax.swing.JTextField();
        txtidcliente = new javax.swing.JTextField();
        txtidempleado = new javax.swing.JTextField();
        txtidped = new javax.swing.JTextField();
        txtfpedido = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtbuscarporid = new javax.swing.JTextField();
        lblname2 = new javax.swing.JLabel();
        txtbucarporcompania = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscar = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lblRegion = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        txtregdest = new javax.swing.JTextField();
        txtcodpostdes = new javax.swing.JTextField();
        txtpaisdest = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnElminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(706, 785));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(105, 79, 560, 10);

        lblMantenimiento.setText("Mantenimiento");
        getContentPane().add(lblMantenimiento);
        lblMantenimiento.setBounds(10, 64, 84, 16);

        lblBusqueda.setText("Búsqueda");
        getContentPane().add(lblBusqueda);
        lblBusqueda.setBounds(0, 484, 70, 16);

        lblPedido.setText("Id Pedido");
        getContentPane().add(lblPedido);
        lblPedido.setBounds(120, 110, 53, 16);

        lblCliente.setText("Id Cliente");
        getContentPane().add(lblCliente);
        lblCliente.setBounds(110, 150, 54, 20);

        lblEmpleado.setText("Id Empleado");
        getContentPane().add(lblEmpleado);
        lblEmpleado.setBounds(90, 190, 71, 20);

        lblPedido2.setText("Fecha Pedido");
        getContentPane().add(lblPedido2);
        lblPedido2.setBounds(80, 220, 76, 20);

        lblEntrega.setText("Fecha Entrega");
        getContentPane().add(lblEntrega);
        lblEntrega.setBounds(90, 250, 82, 20);

        lblEnvio.setText("Fecha Envío");
        getContentPane().add(lblEnvio);
        lblEnvio.setBounds(110, 280, 68, 20);

        lblForma.setText("Forma Envío");
        getContentPane().add(lblForma);
        lblForma.setBounds(110, 320, 71, 20);

        lblCargo.setText("Cargo");
        getContentPane().add(lblCargo);
        lblCargo.setBounds(130, 360, 34, 20);

        lblDest.setText("Destinatario");
        getContentPane().add(lblDest);
        lblDest.setBounds(40, 350, 68, 20);

        lblDireccion.setText("Dirección Destinatario");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(60, 400, 124, 20);

        lblCiudad.setText("Ciudad Destinatario");
        getContentPane().add(lblCiudad);
        lblCiudad.setBounds(50, 440, 111, 20);

        txtdirdest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdirdestKeyReleased(evt);
            }
        });
        getContentPane().add(txtdirdest);
        txtdirdest.setBounds(220, 391, 123, 22);

        txtciuddest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtciuddestKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtciuddestKeyTyped(evt);
            }
        });
        getContentPane().add(txtciuddest);
        txtciuddest.setBounds(220, 420, 123, 22);

        txtdestinatario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdestinatarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdestinatarioKeyTyped(evt);
            }
        });
        getContentPane().add(txtdestinatario);
        txtdestinatario.setBounds(220, 362, 123, 22);

        txtcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcargoActionPerformed(evt);
            }
        });
        txtcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcargoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcargoKeyTyped(evt);
            }
        });
        getContentPane().add(txtcargo);
        txtcargo.setBounds(220, 333, 123, 22);

        txtformaenvio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtformaenvioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtformaenvioKeyTyped(evt);
            }
        });
        getContentPane().add(txtformaenvio);
        txtformaenvio.setBounds(220, 304, 123, 22);

        txtfeenvio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfeenvioKeyReleased(evt);
            }
        });
        getContentPane().add(txtfeenvio);
        txtfeenvio.setBounds(220, 275, 123, 22);

        txtfentrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfentregaKeyReleased(evt);
            }
        });
        getContentPane().add(txtfentrega);
        txtfentrega.setBounds(220, 235, 123, 22);

        txtidcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidclienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidclienteKeyTyped(evt);
            }
        });
        getContentPane().add(txtidcliente);
        txtidcliente.setBounds(220, 140, 123, 22);

        txtidempleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidempleadoKeyTyped(evt);
            }
        });
        getContentPane().add(txtidempleado);
        txtidempleado.setBounds(220, 175, 123, 22);

        txtidped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpedActionPerformed(evt);
            }
        });
        txtidped.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidpedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidpedKeyTyped(evt);
            }
        });
        getContentPane().add(txtidped);
        txtidped.setBounds(220, 100, 123, 22);

        txtfpedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfpedidoKeyReleased(evt);
            }
        });
        getContentPane().add(txtfpedido);
        txtfpedido.setBounds(220, 204, 123, 22);

        lblID.setText("Id Ped");
        getContentPane().add(lblID);
        lblID.setBounds(110, 534, 36, 16);

        txtbuscarporid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarporidActionPerformed(evt);
            }
        });
        txtbuscarporid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarporidKeyReleased(evt);
            }
        });
        getContentPane().add(txtbuscarporid);
        txtbuscarporid.setBounds(170, 534, 123, 22);

        lblname2.setText("Id Cliente");
        getContentPane().add(lblname2);
        lblname2.setBounds(330, 534, 54, 16);

        txtbucarporcompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbucarporcompaniaActionPerformed(evt);
            }
        });
        txtbucarporcompania.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbucarporcompaniaKeyReleased(evt);
            }
        });
        getContentPane().add(txtbucarporcompania);
        txtbucarporcompania.setBounds(450, 534, 123, 22);

        tblBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuscar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(115, 586, 452, 94);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(83, 494, 580, 16);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(665, 79, 50, 650);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 734, 664, 54);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(0, 514, 50, 220);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(2, 92, 50, 378);

        lblRegion.setText("Región Destinatario");
        getContentPane().add(lblRegion);
        lblRegion.setBounds(363, 103, 111, 16);

        lblCodigo.setText("Cod Postal Dest");
        getContentPane().add(lblCodigo);
        lblCodigo.setBounds(385, 143, 89, 16);

        lblPais.setText("País Destinatario");
        getContentPane().add(lblPais);
        lblPais.setBounds(379, 172, 95, 16);

        txtregdest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtregdestKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtregdestKeyTyped(evt);
            }
        });
        getContentPane().add(txtregdest);
        txtregdest.setBounds(492, 100, 123, 22);

        txtcodpostdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodpostdesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodpostdesKeyTyped(evt);
            }
        });
        getContentPane().add(txtcodpostdes);
        txtcodpostdes.setBounds(492, 140, 123, 22);

        txtpaisdest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpaisdestKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpaisdestKeyTyped(evt);
            }
        });
        getContentPane().add(txtpaisdest);
        txtpaisdest.setBounds(492, 169, 123, 22);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(12, 2, 28, 35);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(47, 2, 28, 35);

        btnElminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/eliminar.png"))); // NOI18N
        btnElminar.setText("Eliminar");
        btnElminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnElminar);
        btnElminar.setBounds(117, 2, 28, 35);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(82, 2, 28, 37);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/impresora.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        getContentPane().add(btnImprimir);
        btnImprimir.setBounds(152, 2, 28, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcargoActionPerformed

    private void txtidpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpedActionPerformed

    private void txtbuscarporidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarporidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarporidActionPerformed

    private void txtbucarporcompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbucarporcompaniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbucarporcompaniaActionPerformed

    private void txtformaenvioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtformaenvioKeyTyped
     char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo números");
        }
        txtformaenvio.setText(txtformaenvio.getText().toUpperCase());
        
        
    }//GEN-LAST:event_txtformaenvioKeyTyped

    private void txtcargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcargoKeyTyped
   char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo números");
        }
        txtcargo.setText(txtcargo.getText().toUpperCase());
    }//GEN-LAST:event_txtcargoKeyTyped

    private void txtdestinatarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdestinatarioKeyTyped
       char validar=evt.getKeyChar();
        if(Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
        txtdestinatario.setText(txtdestinatario.getText().toUpperCase());
    }//GEN-LAST:event_txtdestinatarioKeyTyped

    private void txtciuddestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciuddestKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
         txtciuddest.setText( txtciuddest.getText().toUpperCase());
    }//GEN-LAST:event_txtciuddestKeyTyped

    private void txtregdestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtregdestKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
         txtregdest.setText( txtregdest.getText().toUpperCase());
    }//GEN-LAST:event_txtregdestKeyTyped

    private void txtpaisdestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaisdestKeyTyped
         char validar=evt.getKeyChar();
        if(Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
         txtpaisdest.setText( txtpaisdest.getText().toUpperCase());
    }//GEN-LAST:event_txtpaisdestKeyTyped

    private void txtidpedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpedKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtidpedKeyTyped

    private void txtidclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidclienteKeyTyped
       char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtidclienteKeyTyped

    private void txtidempleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyTyped
      char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtidempleadoKeyTyped

    private void txtcodpostdesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodpostdesKeyTyped
       char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtcodpostdesKeyTyped

    private void txtidpedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidpedKeyReleased
Habilitarbtn();        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpedKeyReleased

    private void txtidclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidclienteKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtidclienteKeyReleased

    private void txtidempleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidempleadoKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtidempleadoKeyReleased

    private void txtfpedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfpedidoKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtfpedidoKeyReleased

    private void txtfentregaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfentregaKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtfentregaKeyReleased

    private void txtfeenvioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfeenvioKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtfeenvioKeyReleased

    private void txtformaenvioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtformaenvioKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtformaenvioKeyReleased

    private void txtcargoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcargoKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtcargoKeyReleased

    private void txtdestinatarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdestinatarioKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtdestinatarioKeyReleased

    private void txtdirdestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdirdestKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtdirdestKeyReleased

    private void txtciuddestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtciuddestKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtciuddestKeyReleased

    private void txtregdestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtregdestKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtregdestKeyReleased

    private void txtcodpostdesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodpostdesKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtcodpostdesKeyReleased

    private void txtpaisdestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaisdestKeyReleased
Habilitarbtn();             // TODO add your handling code here:
    }//GEN-LAST:event_txtpaisdestKeyReleased

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       Pedidos pedidos = new Pedidos("root","Daniela23<3171561","neptuno", "localhost:3308");
        pedidos.conectarPedidos();
        JOptionPane.showMessageDialog(null, pedidos.guardarPedidos(txtidped.getText(),txtidcliente.getText(),txtidempleado.getText(),txtfpedido.getText()
    ,txtfentrega.getText(),txtfeenvio.getText(),txtformaenvio.getText(),txtcargo.getText(),txtdestinatario.getText(),txtdirdest.getText(),
    txtciuddest.getText(),txtregdest.getText(),txtcodpostdes.getText(),txtpaisdest.getText())); 
        pedidos.cerrar();
        

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
         Pedidos pedidos = new Pedidos("root","Daniela23<3171561","neptuno", "localhost:3308");
        pedidos.conectarPedidos();
        JOptionPane.showMessageDialog(null, pedidos.modificarPedidos(txtidped.getText(),txtidcliente.getText(),txtidempleado.getText(),txtfpedido.getText()
    ,txtfentrega.getText(),txtfeenvio.getText(),txtformaenvio.getText(),txtcargo.getText(),txtdestinatario.getText(),txtdirdest.getText(),
    txtciuddest.getText(),txtregdest.getText(),txtcodpostdes.getText(),txtpaisdest.getText())); 
        pedidos.cerrar();
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnElminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarActionPerformed
        Pedidos pedidos = new Pedidos("root","Daniela23<3171561","neptuno", "localhost:3308");
        pedidos.conectarPedidos();
        JOptionPane.showMessageDialog(null, pedidos.eliminarPedidos(txtidped.getText())); 
        pedidos.cerrar();
    }//GEN-LAST:event_btnElminarActionPerformed

    private void txtbuscarporidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarporidKeyReleased
        try {
            // TODO add your handling code here:
           Pedidos pedidos = new Pedidos("root","Daniela23<3171561","neptuno", "localhost:3308");
        pedidos.conectarPedidos();
            ResultSet rsCliente = pedidos.buscarPorId(txtbuscarporid.getText());
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel(); //crear el esquema de la tabal que se va a crear
            tblBuscar.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            ResultSetMetaData rsMd = rsCliente.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            //Creando las filas para el JTable
            while (rsCliente.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rsCliente.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            pedidos.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_txtbuscarporidKeyReleased

    private void txtbucarporcompaniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbucarporcompaniaKeyReleased
              try {
            // TODO add your handling code here:
           Pedidos pedidos = new Pedidos("root","Daniela23<3171561","neptuno", "localhost:3308");
        pedidos.conectarPedidos();
            ResultSet rsCliente = pedidos.buscarPorIdc(txtbucarporcompania.getText());
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel(); //crear el esquema de la tabal que se va a crear
            tblBuscar.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            ResultSetMetaData rsMd = rsCliente.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            //Creando las filas para el JTable
            while (rsCliente.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rsCliente.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            pedidos.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtbucarporcompaniaKeyReleased

    private void tblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscarMouseClicked
           btnGuardar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnElminar.setEnabled(true);
    
               System.out.println(""+tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 1));
        
        this.txtidped.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 0).toString());
        this.txtidcliente.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 1).toString());
        this.txtidempleado.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 2).toString());
        this.txtfpedido.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 3).toString());
        this.txtfentrega.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 4).toString());
//        this.txtfeenvio.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 5).toString());
        
       this.txtformaenvio.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 6).toString());
        this.txtcargo.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 7).toString());
        this.txtdestinatario.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 8).toString());
        this.txtdirdest.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 9).toString());
        this.txtciuddest.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 10).toString());
//          this.txtregdest.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 11).toString());
        this.txtcodpostdes.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 12).toString());
          this.txtpaisdest.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 13).toString());

        
        
        
        
    }//GEN-LAST:event_tblBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDest;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblEntrega;
    private javax.swing.JLabel lblEnvio;
    private javax.swing.JLabel lblForma;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMantenimiento;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblPedido2;
    private javax.swing.JLabel lblRegion;
    private javax.swing.JLabel lblname2;
    private javax.swing.JTable tblBuscar;
    private javax.swing.JTextField txtbucarporcompania;
    private javax.swing.JTextField txtbuscarporid;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtciuddest;
    private javax.swing.JTextField txtcodpostdes;
    private javax.swing.JTextField txtdestinatario;
    private javax.swing.JTextField txtdirdest;
    private javax.swing.JTextField txtfeenvio;
    private javax.swing.JTextField txtfentrega;
    private javax.swing.JTextField txtformaenvio;
    private javax.swing.JTextField txtfpedido;
    private javax.swing.JTextField txtidcliente;
    private javax.swing.JTextField txtidempleado;
    private javax.swing.JTextField txtidped;
    private javax.swing.JTextField txtpaisdest;
    private javax.swing.JTextField txtregdest;
    // End of variables declaration//GEN-END:variables
}
