package neptuno;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author User
 */
public class FrmProductos extends javax.swing.JInternalFrame {

String idProveedor;
String idCat;
    public FrmProductos() {
        initComponents();
        JButton[] botones={btnNuevo,btnGuardar,btnModificar,btnElminar,btnImprimir};
        JLabel[] label1={lblIdProducto,lblname,lblIdprov,lblIdcat,lblCantxu,lblPrecioxU,lblUnidades,lblUnidadesxped,lblNivel,lblSuspendido,lblfds};
        JTextField[] texto1={txtidprod,txtnombreprod,txtidproov,txtidcat,txtcantxuni,txtpreciouni,txtunixexis,txtunixped,txtnewped,txtsusp,txtfds};
        JTextField[] texto2={txtbuscarporid,txtbucarporcompania};
        JLabel[] label2={lblID,lblname2};
        int separacion=30;
        this.getContentPane().setBackground(Color.white);
        
        jSeparator1.setBounds(105, 70, 570, 10);
jSeparator3.setBounds(675, 70, 10, 660);
jSeparator4.setBounds(10, 728, 665, 10);
jSeparator6.setBounds(10, 500, 10, 230);
jSeparator7.setBounds(10, 75, 10, 400);
jSeparator2.setBounds(80, 490, 595, 10);

lblMantenimiento.setBounds(12, 57, 100, 20);
lblBusqueda.setBounds(12, 478, 100, 20);
btnGuardar.setEnabled(false);
btnModificar.setEnabled(false);
btnElminar.setEnabled(false);
btnImprimir.setEnabled(false);
        for(JButton btn:botones)
        {
            btn.setBounds(separacion,20,30,30);
            separacion+=30;
        }
        
        separacion=90;
        for(JLabel lbl:label1)
        {
            lbl.setBounds(200,separacion,150,30);
            separacion+=35;
        }
        separacion=100;
           for(JTextField txt:texto1)
        {
            txt.setBounds(375,separacion,150,20);
            separacion+=35;
        }
           cbxprov.setBounds(375, 170, 150, 20);
           cbxcat.setBounds(375, 205, 150, 20);
           spn.setBounds(375, 345, 150, 20);
           
           
           
           
            separacion=160;
          for(JTextField txt:texto2)
        {
            txt.setBounds(separacion,535,100,20);
            separacion+=310;
        }
          
        separacion=70;
        for(JLabel lbl:label2)
        {
            lbl.setBounds(separacion,525,120,30);
            separacion+=300;
        }
        
        txtidproov.setBounds(1000, 1000, 595, 10);
txtidcat.setBounds(1000, 1000, 595, 10);
txtunixped.setBounds(1000, 1000, WIDTH, WIDTH);
    }
    
            public void Habilitarbtn()
    {
     
         JTextField[] texto1={txtidprod,txtnombreprod,txtidproov,txtidcat,txtcantxuni,txtpreciouni,txtunixexis,txtunixped,txtnewped,txtsusp,txtfds};    
           
       if(!texto1[0].getText().isEmpty() && !texto1[1].getText().isEmpty() && 
           !texto1[4].getText().isEmpty() && !texto1[5].getText().isEmpty() &&
          !texto1[6].getText().isEmpty() && !texto1[7].getText().isEmpty() && !texto1[8].getText().isEmpty() &&
          !texto1[9].getText().isEmpty() && !texto1[10].getText().isEmpty())
       {
           btnGuardar.setEnabled(true);
       }
       else{
           btnGuardar.setEnabled(false);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblMantenimiento = new javax.swing.JLabel();
        lblBusqueda = new javax.swing.JLabel();
        lblIdProducto = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();
        lblIdprov = new javax.swing.JLabel();
        lblIdcat = new javax.swing.JLabel();
        lblCantxu = new javax.swing.JLabel();
        lblPrecioxU = new javax.swing.JLabel();
        lblUnidades = new javax.swing.JLabel();
        lblUnidadesxped = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblSuspendido = new javax.swing.JLabel();
        lblfds = new javax.swing.JLabel();
        txtsusp = new javax.swing.JTextField();
        txtfds = new javax.swing.JTextField();
        txtnewped = new javax.swing.JTextField();
        txtunixped = new javax.swing.JTextField();
        txtunixexis = new javax.swing.JTextField();
        txtpreciouni = new javax.swing.JTextField();
        txtcantxuni = new javax.swing.JTextField();
        txtnombreprod = new javax.swing.JTextField();
        txtidproov = new javax.swing.JTextField();
        txtidprod = new javax.swing.JTextField();
        txtidcat = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtbuscarporid = new javax.swing.JTextField();
        lblname2 = new javax.swing.JLabel();
        txtbucarporcompania = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuscar = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnElminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        cbxcat = new javax.swing.JComboBox<>();
        cbxprov = new javax.swing.JComboBox<>();
        spn = new javax.swing.JSpinner();
        cbxSuspendido = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(706, 785));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(115, 75, 560, 10);

        lblMantenimiento.setText("Mantenimiento");
        getContentPane().add(lblMantenimiento);
        lblMantenimiento.setBounds(20, 60, 84, 16);

        lblBusqueda.setText("Búsqueda");
        getContentPane().add(lblBusqueda);
        lblBusqueda.setBounds(10, 480, 70, 16);

        lblIdProducto.setText("Id Producto");
        getContentPane().add(lblIdProducto);
        lblIdProducto.setBounds(246, 106, 65, 16);

        lblname.setText("Nombre Prodcuto");
        getContentPane().add(lblname);
        lblname.setBounds(212, 132, 99, 16);

        lblIdprov.setText("Id Proveedor");
        getContentPane().add(lblIdprov);
        lblIdprov.setBounds(238, 173, 73, 16);

        lblIdcat.setText("Id Categoría");
        getContentPane().add(lblIdcat);
        lblIdcat.setBounds(241, 207, 70, 16);

        lblCantxu.setText("Cantidad por Unidad");
        getContentPane().add(lblCantxu);
        lblCantxu.setBounds(195, 241, 116, 16);

        lblPrecioxU.setText("Precio Unidad");
        getContentPane().add(lblPrecioxU);
        lblPrecioxU.setBounds(233, 275, 78, 16);

        lblUnidades.setText("Unidades en Existencia");
        getContentPane().add(lblUnidades);
        lblUnidades.setBounds(181, 305, 130, 16);

        lblUnidadesxped.setText("Unidades en Pedido");
        getContentPane().add(lblUnidadesxped);
        lblUnidadesxped.setBounds(199, 340, 112, 16);

        lblNivel.setText("Nivel Nuevo Pedido");
        getContentPane().add(lblNivel);
        lblNivel.setBounds(203, 369, 108, 16);

        lblSuspendido.setText("Suspendido");
        getContentPane().add(lblSuspendido);
        lblSuspendido.setBounds(245, 397, 66, 16);

        lblfds.setText("Fds");
        getContentPane().add(lblfds);
        lblfds.setBounds(291, 431, 20, 16);

        txtsusp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsuspKeyReleased(evt);
            }
        });
        getContentPane().add(txtsusp);
        txtsusp.setBounds(359, 397, 123, 22);

        txtfds.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfdsKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfdsKeyTyped(evt);
            }
        });
        getContentPane().add(txtfds);
        txtfds.setBounds(359, 426, 123, 22);

        txtnewped.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnewpedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnewpedKeyTyped(evt);
            }
        });
        getContentPane().add(txtnewped);
        txtnewped.setBounds(359, 363, 123, 22);

        txtunixped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunixpedActionPerformed(evt);
            }
        });
        txtunixped.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtunixpedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtunixpedKeyTyped(evt);
            }
        });
        getContentPane().add(txtunixped);
        txtunixped.setBounds(500, 300, 123, 22);

        txtunixexis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtunixexisKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtunixexisKeyTyped(evt);
            }
        });
        getContentPane().add(txtunixexis);
        txtunixexis.setBounds(359, 299, 123, 22);

        txtpreciouni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpreciouniKeyReleased(evt);
            }
        });
        getContentPane().add(txtpreciouni);
        txtpreciouni.setBounds(359, 270, 123, 22);

        txtcantxuni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantxuniKeyReleased(evt);
            }
        });
        getContentPane().add(txtcantxuni);
        txtcantxuni.setBounds(359, 241, 123, 22);

        txtnombreprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreprodKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreprodKeyTyped(evt);
            }
        });
        getContentPane().add(txtnombreprod);
        txtnombreprod.setBounds(359, 132, 123, 22);

        txtidproov.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidproovKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidproovKeyTyped(evt);
            }
        });
        getContentPane().add(txtidproov);
        txtidproov.setBounds(530, 90, 123, 22);

        txtidprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidprodActionPerformed(evt);
            }
        });
        txtidprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidprodKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidprodKeyTyped(evt);
            }
        });
        getContentPane().add(txtidprod);
        txtidprod.setBounds(359, 103, 123, 22);

        txtidcat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidcatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidcatKeyTyped(evt);
            }
        });
        getContentPane().add(txtidcat);
        txtidcat.setBounds(530, 130, 123, 22);

        lblID.setText("Id Proveedor");
        getContentPane().add(lblID);
        lblID.setBounds(120, 530, 73, 16);

        txtbuscarporid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarporidActionPerformed(evt);
            }
        });
        txtbuscarporid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarporidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarporidKeyTyped(evt);
            }
        });
        getContentPane().add(txtbuscarporid);
        txtbuscarporid.setBounds(180, 530, 123, 22);

        lblname2.setText("Nombre Prod.");
        getContentPane().add(lblname2);
        lblname2.setBounds(360, 530, 70, 16);

        txtbucarporcompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbucarporcompaniaActionPerformed(evt);
            }
        });
        txtbucarporcompania.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbucarporcompaniaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbucarporcompaniaKeyTyped(evt);
            }
        });
        getContentPane().add(txtbucarporcompania);
        txtbucarporcompania.setBounds(460, 530, 123, 22);

        tblBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBuscarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuscar);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(125, 582, 452, 94);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(93, 490, 580, 16);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(675, 75, 50, 650);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(10, 730, 664, 54);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(10, 510, 50, 220);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(12, 88, 50, 378);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(12, 2, 28, 35);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(47, 2, 28, 35);

        btnElminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/eliminar.png"))); // NOI18N
        btnElminar.setText("Eliminar");
        btnElminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnElminar);
        btnElminar.setBounds(117, 2, 28, 35);

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(82, 2, 28, 37);

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neptuno/impresora.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        getContentPane().add(btnImprimir);
        btnImprimir.setBounds(152, 2, 28, 35);

        cbxcat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxcatItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxcat);
        cbxcat.setBounds(380, 200, 160, 22);

        cbxprov.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxprovItemStateChanged(evt);
            }
        });
        cbxprov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxprovMouseClicked(evt);
            }
        });
        getContentPane().add(cbxprov);
        cbxprov.setBounds(380, 170, 160, 22);
        getContentPane().add(spn);
        spn.setBounds(380, 340, 100, 22);

        cbxSuspendido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSuspendidoActionPerformed(evt);
            }
        });
        getContentPane().add(cbxSuspendido);
        cbxSuspendido.setBounds(530, 410, 30, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtunixpedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunixpedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunixpedActionPerformed

    private void txtidprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprodActionPerformed

    private void txtbuscarporidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarporidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarporidActionPerformed

    private void txtbucarporcompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbucarporcompaniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbucarporcompaniaActionPerformed

    private void txtnombreprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreprodKeyTyped
          char validar=evt.getKeyChar();
        if(Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
         txtnombreprod.setText( txtnombreprod.getText().toUpperCase());
    }//GEN-LAST:event_txtnombreprodKeyTyped

    private void txtnewpedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewpedKeyTyped
      char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
         txtnewped.setText( txtnewped.getText().toUpperCase());
    }//GEN-LAST:event_txtnewpedKeyTyped

    private void txtfdsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfdsKeyTyped
       char validar=evt.getKeyChar();
        if(Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
          txtfds.setText(  txtfds.getText().toUpperCase());
    }//GEN-LAST:event_txtfdsKeyTyped

    private void txtbucarporcompaniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbucarporcompaniaKeyTyped
      char validar=evt.getKeyChar();
        if(Character.isDigit(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo letras");
        }
         txtbucarporcompania.setText( txtbucarporcompania.getText().toUpperCase());
    }//GEN-LAST:event_txtbucarporcompaniaKeyTyped

    private void txtidprodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidprodKeyTyped
      char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtidprodKeyTyped

    private void txtunixexisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunixexisKeyTyped
     char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtunixexisKeyTyped

    private void txtunixpedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunixpedKeyTyped
       char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
             JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtunixpedKeyTyped

    private void txtbuscarporidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarporidKeyTyped
  
    }//GEN-LAST:event_txtbuscarporidKeyTyped

    private void txtidprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidprodKeyReleased
Habilitarbtn();        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprodKeyReleased

    private void txtnombreprodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreprodKeyReleased
Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreprodKeyReleased

    private void txtcantxuniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantxuniKeyReleased
Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtcantxuniKeyReleased

    private void txtpreciouniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpreciouniKeyReleased
Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtpreciouniKeyReleased

    private void txtunixexisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunixexisKeyReleased
Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtunixexisKeyReleased

    private void txtunixpedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunixpedKeyReleased
Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtunixpedKeyReleased

    private void txtnewpedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnewpedKeyReleased
Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtnewpedKeyReleased

    private void txtsuspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsuspKeyReleased
Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtsuspKeyReleased

    private void txtfdsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfdsKeyReleased
Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtfdsKeyReleased

    private void txtidcatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidcatKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtidcatKeyTyped

    private void txtidcatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidcatKeyReleased
        Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtidcatKeyReleased

    private void txtidproovKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidproovKeyTyped
        char validar=evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"Ingrese solo numeros");
        }
    }//GEN-LAST:event_txtidproovKeyTyped

    private void txtidproovKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidproovKeyReleased
        Habilitarbtn();         // TODO add your handling code here:
    }//GEN-LAST:event_txtidproovKeyReleased

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    
        try {
            Productos productos = new Productos("root","Daniela23<3171561","neptuno","localhost:3308");
            productos.conectarProductos();
            ResultSet rsProveedores =productos.cargarProveedores();
           
            
            while(rsProveedores.next())
            {
                cbxprov.addItem(rsProveedores.getObject(1).toString());
            }
            
             ResultSet rsCategorias =productos.cargarCategorias();
            while(rsCategorias.next())
            {
                cbxcat.addItem(rsCategorias.getObject(1).toString());
            }
            
            productos.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(FrmProductos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void txtbuscarporidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarporidKeyReleased
              
   try {
            // TODO add your handling code here:
            Productos productos = new Productos("root","Daniela23<3171561","neptuno","localhost:3308");
            productos.conectarProductos();
            ResultSet rsCliente = productos.buscarPorId(txtbuscarporid.getText());
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel(); //crear el esquema de la tabal que se va a crear
            tblBuscar.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            ResultSetMetaData rsMd = rsCliente.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            //Creando las filas para el JTable
            while (rsCliente.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rsCliente.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            productos.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_txtbuscarporidKeyReleased

    private void cbxprovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxprovMouseClicked
 
  
    }//GEN-LAST:event_cbxprovMouseClicked

    private void cbxprovItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxprovItemStateChanged
 
          try {
        Productos productos = new Productos("root","Daniela23<3171561","neptuno", "localhost:3308");
        productos.conectarProductos();
        ResultSet rsProveedor = productos.consultarProveedor(cbxprov.getSelectedItem().toString());
        while (rsProveedor.next())
        {
            idProveedor = rsProveedor.getObject(1).toString();
            System.out.println(idProveedor);
        }
        productos.cerrar();
    } catch (SQLException ex) {
        Logger.getLogger(FrmProductos.class.getName()).log(Level.SEVERE, null, ex);
    }

        
    }//GEN-LAST:event_cbxprovItemStateChanged

    private void cbxcatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxcatItemStateChanged
         try {
        Productos productos = new Productos("root","Daniela23<3171561","neptuno", "localhost:3308");
        productos.conectarProductos();
        ResultSet rsCategoria = productos.consultarCategoria(cbxcat.getSelectedItem().toString());
        while (rsCategoria.next())
        {
            idCat = rsCategoria.getObject(1).toString();
            System.out.println(idCat);
           
        }
        productos.cerrar();
    } catch (SQLException ex) {
        Logger.getLogger(FrmProductos.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_cbxcatItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
  int value = (Integer) spn.getValue();
  String valor= String.valueOf(value);
  txtcantxuni.setText(valor);
        
        
        Productos productos = new Productos("root","Daniela23<3171561","neptuno", "localhost:3308");
        productos.conectarProductos();
        JOptionPane.showMessageDialog(null, productos.guardarProducto(txtidprod.getText(),txtnombreprod.getText(),
//                cbxprov.getSelectedItem().toString(),cbxcat.getSelectedItem().toString()
    txtcantxuni.getText(),txtpreciouni.getText(),txtunixexis.getText(),txtunixped.getText(),
    txtnewped.getText(),txtsusp.getText())); 
        productos.cerrar();
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void tblBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBuscarMouseClicked
        btnModificar.setEnabled(true);
        btnElminar.setEnabled(true);
        
        this.txtidprod.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 0).toString());
        this.txtnombreprod.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 1).toString());

        this.txtcantxuni.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 4).toString());
        this.txtpreciouni.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 5).toString());
        
//      this.txtregion.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 6).toString());
        this.txtunixexis.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 6).toString());
        
        
        
        
        this.txtunixped.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 7).toString());
        this.txtnewped.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 8).toString());
        this.txtsusp.setText(tblBuscar.getValueAt(tblBuscar.getSelectedRow(), 9).toString());
        
        spn.setValue(Integer.parseInt(txtunixped.getText()));
        
     
   
    }//GEN-LAST:event_tblBuscarMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
       
        Productos productos = new Productos("root","Daniela23<3171561","neptuno", "localhost:3308");
        productos.conectarProductos();
             JOptionPane.showMessageDialog(null, productos.modificarProducto(txtidprod.getText(),txtnombreprod.getText(),
//                cbxprov.getSelectedItem().toString(),cbxcat.getSelectedItem().toString()
    txtcantxuni.getText(),txtpreciouni.getText(),txtunixexis.getText(),txtunixped.getText(),
    txtnewped.getText())); 
        productos.cerrar();
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnElminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElminarActionPerformed
       
        
          Productos productos = new Productos("root","Daniela23<3171561","neptuno", "localhost:3308");
        productos.conectarProductos();
        JOptionPane.showMessageDialog(null, productos.eliminarProducto(txtidprod.getText()) ); 
        productos.cerrar();
    }//GEN-LAST:event_btnElminarActionPerformed

    private void txtbucarporcompaniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbucarporcompaniaKeyReleased
      
        try {
            // TODO add your handling code here:
            Productos productos = new Productos("root","Daniela23<3171561","neptuno","localhost:3308");
            productos.conectarProductos();
            ResultSet rsCliente = productos.buscarPorNombre(txtbucarporcompania.getText());
            //Para establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel(); //crear el esquema de la tabal que se va a crear
            tblBuscar.setModel(modelo);
            //Para conectarnos a nuestra base de datos
            ResultSetMetaData rsMd = rsCliente.getMetaData();
            //La cantidad de columnas que tiene la consulta
            int cantidadColumnas = rsMd.getColumnCount();
            //Establecer como cabezeras el nombre de las colimnas
            for (int i = 1; i <= cantidadColumnas; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            //Creando las filas para el JTable
            while (rsCliente.next()) {
                Object[] fila = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i]=rsCliente.getObject(i+1);
                }
                modelo.addRow(fila);
            }
            productos.cerrar();
        } catch (SQLException ex) {
            Logger.getLogger(FrmClientes.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        
    }//GEN-LAST:event_txtbucarporcompaniaKeyReleased

    private void cbxSuspendidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSuspendidoActionPerformed
       if(cbxSuspendido.isSelected())
       {
           txtsusp.setText("1");
       }
       else
       {
            txtsusp.setText("0");
       }
    }//GEN-LAST:event_cbxSuspendidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox cbxSuspendido;
    private javax.swing.JComboBox<String> cbxcat;
    private javax.swing.JComboBox<String> cbxprov;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblBusqueda;
    private javax.swing.JLabel lblCantxu;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblIdcat;
    private javax.swing.JLabel lblIdprov;
    private javax.swing.JLabel lblMantenimiento;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblPrecioxU;
    private javax.swing.JLabel lblSuspendido;
    private javax.swing.JLabel lblUnidades;
    private javax.swing.JLabel lblUnidadesxped;
    private javax.swing.JLabel lblfds;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname2;
    private javax.swing.JSpinner spn;
    private javax.swing.JTable tblBuscar;
    private javax.swing.JTextField txtbucarporcompania;
    private javax.swing.JTextField txtbuscarporid;
    private javax.swing.JTextField txtcantxuni;
    private javax.swing.JTextField txtfds;
    private javax.swing.JTextField txtidcat;
    private javax.swing.JTextField txtidprod;
    private javax.swing.JTextField txtidproov;
    private javax.swing.JTextField txtnewped;
    private javax.swing.JTextField txtnombreprod;
    private javax.swing.JTextField txtpreciouni;
    private javax.swing.JTextField txtsusp;
    private javax.swing.JTextField txtunixexis;
    private javax.swing.JTextField txtunixped;
    // End of variables declaration//GEN-END:variables
}
